# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
name:                stic
version:             0.1.0.0
github:              "Martinsos/wabi"
#license:             BSD3
author:              "Stic"
maintainer:          "info@stic.dev"
copyright:           "2019 Stic"

extra-source-files:
  - README.md
  - ChangeLog.md

data-dir: data/
data-files:
  - Generator/templates/**/*

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Martinsos/stic#readme>

dependencies:
  - base >= 4.7 && < 5

ghc-options:
  - -Wall
  - -Werror

library:
  source-dirs: src
  dependencies:
    - filepath
    - parsec
    - mustache
    - text
    - aeson
    - directory
    - split

executables:
  stic-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - stic

benchmarks:
  stic-benchmarks:
    main:                Main.hs
    source-dirs:         benchmark
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - stic
      - criterion

tests:
  stic-test:
    main:                TastyDiscoverDriver.hs
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - aeson
      - filepath
      - text
      - mtl
      - stic
      - tasty
      - tasty-hspec
      - tasty-quickcheck
      - tasty-discover
      - QuickCheck
      - parsec
