- arguments:
  # NOTE: List of extensions below should reflect the list
  #   of default extensions from package.yaml.
  - -XOverloadedStrings
  - -XTemplateHaskell
  - -XQuasiQuotes
  - -XScopedTypeVariables

# TODO: Review the remaining ignored hlint rules.
- ignore: {name: Use camelCase}
- ignore: {name: Eta reduce}
- ignore: {name: Use first} 
- ignore: {name: Use second} 
- ignore: {name: Use newtype instead of data} 
- ignore: {name: Use $>} 
- ignore: {name: Use list comprehension} 